<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>Untitled</title>
  <style type="text/css">
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
  <link rel="stylesheet" href="../assets/css/main.css">
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
  <script src="../assets/js/tests-integration.js"></script>
</head>
<body>










<h2 id="exceptions">Exceptions</h2>
<div class="TODO">
<div class="paragraph">
<p><span class="sentence">TODO(This is a stub)</span></p>
</div>
</div>
<div class="paragraph">
<p><span class="sentence">An <em>exception</em> type declaration is any type declaration that meets the following criteria:</span></p>
</div>
<ul>
<li><span class="sentence">It is a [class or object declaration][Classifier declaration];</span></li>
<li><span class="sentence">It has <code>kotlin.Throwable</code> as supertype;</span></li>
<li><span class="sentence">It has no type parameters.</span></li>
</ul>
<div class="paragraph">
<p><span class="sentence">Any object of an exception type may be <em>thrown</em> or <em>catched</em>.</span></p>
</div>
<h3 id="catching-exceptions">Catching exceptions</h3>
<div class="paragraph">
<p><span class="sentence">A [<code>try</code>-expression][Try-expression] becomes <em>active</em> once the execution of the program enters it and stops being active once the execution of the program leaves it. </span><span class="sentence">If there are several active <code>try</code>-expressions, the one that became active last is <em>currently active</em>.</span></p>
</div>
<div class="paragraph">
<p><span class="sentence">If an exception is thrown while a try-expression is currently active and this try-expression has any <code>catch</code>-blocks, those <code>catch</code>-blocks are checked for applicability for this exception. </span><span class="sentence">A <code>catch</code>-block is applicable for an exception object if the runtime type of this expression object is a subtype of the bound exception parameter of this <code>catch</code>-block. </span><span class="sentence">Note that this is subject to Kotlin [runtime type information][Runtime type information] limitations and may be dependent on the platform implementation of runtime type information, as well as the implementation of exception classes.</span></p>
</div>
<div class="paragraph">
<p><span class="sentence">If a <code>catch</code>-block is applicable for the exception thrown, the code inside the block is evaluated and the value of the block is returned as the value of a <code>try</code>-expression. </span><span class="sentence">If this <code>try</code>-expression contains a <code>finally</code>-block, the body of this block is evaluated after the body of the selected <code>catch</code> block. </span><span class="sentence">The <code>try</code>-expression itself is not considered active inside its own <code>catch</code> and <code>finally</code> blocks. </span><span class="sentence">If this results in throwing other exceptions (including the one caught by the <code>catch</code>-block), they are propagated as normal.</span></p>
</div>
<div class="paragraph">
<p><span class="sentence">If none of the <code>catch</code>-blocks of the currently active <code>try</code>-expression are applicable for the exception, the <code>finally</code> block (if any) is still evaluated and the exception is propagated, meaning that the next active <code>try</code>-expression becomes currently active and is checked for applicability.</span></p>
</div>
<div class="paragraph">
<p><span class="sentence">If there is not a single active <code>try</code>-block, the execution of the program finishes, signaling that the exception has reached top level.</span></p>
</div>
<h3 id="throwing-exceptions">Throwing exceptions</h3>
<div class="paragraph">
<p><span class="sentence">Throwing an exception object is performed using <code>throw</code>-expression. </span><span class="sentence">A valid throw expression <code>throw e</code> requires that:</span></p>
</div>
<ul>
<li><span class="sentence"><code>e</code> is a value of [a runtime-available type][Runtime-available types];</span></li>
<li><span class="sentence"><code>e</code> is a value of an exception type (see above).</span></li>
</ul>
<div class="paragraph">
<p><span class="sentence">Throwing an exception results in checking active <code>try</code>-blocks as described above.</span></p>
</div>
<blockquote>
<div class="paragraph">
<p><span class="sentence">Note: Kotlin does not specify whether throwing exceptions involves construction of a program stack trace and how the actual exception handling is performed internally. </span><span class="sentence">This is a platform-dependent mechanism.</span></p>
</div>
</blockquote>
<div class="TODO">
<div class="paragraph">
<p><span class="sentence">TODO: control flow?</span></p>
</div>
</div>
<div class="TODO">
<div class="paragraph">
<p><span class="sentence">TODO: concurrency?</span></p>
</div>
</div>
<div class="TODO">
<div class="paragraph">
<p><span class="sentence">TODO: write it better</span></p>
</div>
</div>
</body>
</html>
